#!/bin/bash
rm -f "$2/.w3watch/lock"
RESULT="$(/usr/bin/w3watch -c)"

if [[ -n "$RESULT" ]]; then
  echo "$RESULT"
  echo "$RESULT" | /usr/bin/mailx -vs "[W3WATCH] Got new changes" -r w3watch "$1"
fi
